#!/bin/bash

sudo pacman --needed -Sy \
git \
lazygit \
firefox \
ghostty \
ansible \
make cmake


echo "Running nvim playbook"
if ! command -v "nvim" &> /dev/null; then
  ansible-playbook install_nvim.playbook.yml --ask-become-pass
else
  echo "neovim is already installed!"
fi



