#!/bin/bash

# Function to get Docker status
get_docker_status() {
    # Check if Docker daemon is running
    if ! systemctl is-active docker.service &> /dev/null; then
        # Docker daemon is not running
        echo "{\"text\": \"   \", \"class\": \"docker-inactive\", \"tooltip\": \"Docker daemon is not running\"}"
        exit 0
    fi

    # Count running containers
    running_containers=$(docker ps -q | wc -l)

    # Determine icon and class based on number of running containers
    if [[ $running_containers -eq 0 ]]; then
        text=" 0"
        class="docker-no-containers"
        tooltip="Docker daemon is running, but no containers are active"
    else
        text=" $running_containers"
        class="docker-containers-running"
        tooltip=$(docker ps --format "{{.Names}}: {{.Status}}" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
    fi

    # Output JSON for Waybar
    echo "{\"text\": \"$text\", \"class\": \"$class\", \"tooltip\": \"Running containers:\\n$tooltip\"}"
}

# Call the function to output JSON for Waybar
get_docker_status
