{ config, pkgs, lib, ... }:

let
  # Single source for tom's home dir — no /home/tom hardcoding below.
  homeDir = config.users.users.tom.home;

  # Official Bambu Studio from the upstream AppImage (NVIDIA-EGL fixed). The
  # nixpkgs bambu-studio build renders a blank 3D bed here — see the pkg file.
  bambu-studio-appimage = pkgs.callPackage ../../pkgs/bambu-studio-appimage.nix { };
in

# ------------------------------------------------------------------
# minerva-only system config that must SURVIVE a reinstall.
# ------------------------------------------------------------------
# hardware-minerva.nix gets clobbered by nixos-generate-config at
# install time, so anything hand-written for this host lives here
# instead: swap strategy, extra data drives, desktop-only apps.
# (nvidia.nix is the same idea for the GPU stack.)

{
  imports = [
    ./hardware.nix              # generated by nixos-generate-config at install time
    ../../modules/nvidia.nix    # Blackwell dGPU: open module + recent kernel
    ../../modules/code-drive.nix
    ../../modules/storage-drive.nix  # 4TB cold-archive btrfs (label "storage")
    # ollama-cuda is a huge uncached compile. It (and hyprland) hit random
    # cc1plus segfaults during the 2026-07-14 USB-installer build — NOT bad
    # RAM: 3 clean memtest86+ passes cleared it, and the delta was the
    # installer env (BIOS microcode 0x110 vs the installed 0x121; swapless
    # RAM-rootfs installer vs 31G zram here). Builds clean on the installed
    # system. NOTE: ai.nix also provides beads (bd).
    ../../modules/ai.nix      # ollama-cuda, beads — big-GPU host only
    ../../modules/webcam.nix    # EMEET SmartCam S600 tooling + OBS virtual cam
    ../../modules/whisper-dictate.nix  # whisper.cpp voice dictation (F13 toggle)
    ../../modules/root-snapshots.nix   # hourly btrbk snapshots of @ + @home
    # INSTALL DAY: uncomment once the disk is LUKS-partitioned and
    # nixos-generate-config has written the cryptroot device into
    # hardware.nix — the module fails eval without a device (see
    # README "minerva install").
    # ../../modules/luks.nix
  ];

  # ---- Memtest86+ in the boot menu ----------------------------------
  # Added 2026-07-14 after random cc1plus segfaults during the USB-installer
  # reinstall (two hyprland, one ollama ggml-cuda) that built clean on t480.
  # Root cause was installer-env, not hardware: 3 clean memtest86+ passes
  # cleared the RAM, and the installed system (newer microcode 0x121, 31G
  # zram swap) builds the same drvs fine. Tester kept a reboot away anyway.
  boot.loader.systemd-boot.memtest86.enable = true;

  # ---- Ethernet: Killer E5000 5GbE (2026-07-14) --------------------
  # The onboard NIC (PCI 10ec:5000, "Killer E5000") is a rebadged
  # Realtek RTL8126A and the in-kernel r8169 driver drives it fine — but
  # r8169's PCI id-table only auto-matches the plain RTL8126 (10ec:8126),
  # NOT the Killer's 10ec:5000, so nothing bound and no interface was
  # created. Force-load r8169 and feed it the extra id via new_id at
  # boot; enp130s0 then comes up and NetworkManager handles DHCP.
  # Drop this once nixpkgs' kernel carries 10ec:5000 in the id-table.
  boot.kernelModules = [ "r8169" ];
  systemd.services.killer-e5000-bind = {
    description = "Bind r8169 to the Killer E5000 NIC (PCI 10ec:5000)";
    wantedBy = [ "network-pre.target" ];
    before = [ "network-pre.target" ];
    after = [ "systemd-modules-load.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      # new_id rescans and binds all matching unbound devices; a repeat
      # write (id already registered) returns EEXIST, hence `|| true`.
      ExecStart = "${pkgs.bash}/bin/sh -c 'echo 10ec 5000 > /sys/bus/pci/drivers/r8169/new_id || true'";
    };
  };

  # ---- WiFi: off by default (minerva is Ethernet-only) -------------
  # Being dual-homed on WiFi + Ethernet on one subnet caused asymmetric
  # routing / flaky connectivity (it broke the OrcaSlicer <-> A1 printer
  # MQTT session). A desktop only needs the wired Killer NIC above, so switch
  # the radio off at every boot. Re-enable on demand with `nmcli radio wifi
  # on` — it stays on until the next reboot, when this turns it back off.
  systemd.services.disable-wifi = {
    description = "Turn the WiFi radio off at boot (minerva is Ethernet-only)";
    after = [ "NetworkManager.service" ];
    wants = [ "NetworkManager.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.networkmanager}/bin/nmcli radio wifi off";
    };
  };

  # ---- Root snapshots: plain btrfs pool, no LUKS mapper -------------
  # minerva's root is a whole-drive btrfs pool labelled "nixos" (no LUKS);
  # override the module's cryptroot default.
  tomfordweb.root-snapshots.device = "/dev/disk/by-label/nixos";

  # ---- OpenRGB: one daemon for all the RGB bullshit -----------------
  # MSI Mystic Light (Z890 GAMING PLUS WIFI, USB 0db0:0076), Logitech
  # Yeti Orb, GPU/RAM zones over i2c. motherboard="intel" loads
  # i2c-dev + i2c-i801 so SMBus zones are reachable. The Keychron V0
  # Ultra is QMK — OpenRGB only sees it with OpenRGB-QMK firmware;
  # stock firmware stays on VIA. Verify: openrgb --list-devices.
  services.hardware.openrgb = {
    enable = true;
    package = pkgs.openrgb-with-all-plugins;
    motherboard = "intel";
  };

  # ---- Swap: zram, no swap partition -------------------------------
  # 64 GB RAM, zram0. Compressed
  # in-RAM swap; no disk partition to manage.
  zramSwap = {
    enable = true;
    memoryPercent = 50;
  };

  # ---- storage drive lives in modules/storage-drive.nix --------------
  # (WD 4TB died 2026-07-14; replaced with a Fanxiang S101 4TB SSD.)

  # ---- Steam --------------------------------------------------------
  # programs.steam (not home.packages) because it needs the 32-bit
  # graphics stack and system-level driver plumbing.
  programs.steam = {
    enable = true;
    remotePlay.openFirewall = false;
  };
  hardware.graphics.enable32Bit = true;

  # ---- OpenTabletDriver — input device config/firmware via its GUI.
  hardware.opentabletdriver.enable = true;

  # ---- ollama + beads live in modules/ai.nix ------------------------

  # ---- SMB share on the GL.iNet router (was ops/local.smb_mount.yml) -
  # Credentials must NOT live in the nix store. One-time post-install:
  #   sudo mkdir -p /etc/nixos-secrets
  #   printf 'username=dubious\npassword=%s\n' \
  #     "$(op read 'op://tomfordweb/Dubious Samba/password')" \
  #     | sudo tee /etc/nixos-secrets/dubious-smb >/dev/null
  #   sudo chmod 600 /etc/nixos-secrets/dubious-smb
  fileSystems."/mnt/dubious-smb" = {
    device = "//192.168.8.1/dubious";
    fsType = "cifs";
    options = [
      "credentials=/etc/nixos-secrets/dubious-smb"
      "uid=1000"
      "gid=1000"
      "nofail"
      "noauto"
      # soft is the kernel default, but declare it: a hard CIFS mount on a
      # flaky router hangs processes uninterruptibly instead of erroring.
      "soft"
      "x-systemd.automount"
      # The automount trigger fires on any stat of /mnt/* (ls -l, tab
      # completion, a file manager). If the router is asleep or off, the
      # default 90s mount timeout is what freezes /mnt. This host's mount
      # currently costs ~25s in SessSetup, so the cap has to clear that.
      "x-systemd.mount-timeout=45s"
      # No idle-timeout on purpose. Every unmount makes the next stat of /mnt
      # pay a fresh mount, so a short idle window turns one slow mount into a
      # slow mount per command. Mount once, keep it.
    ];
  };

  # The kernel registers the cifs.spnego and dns_resolver key types, then
  # upcalls to request-key when CIFS needs them. nixpkgs' cifs-utils ships no
  # request-key config and NixOS creates no /etc/request-key.conf, so those
  # upcalls land nowhere. Wire the handlers, and negate everything else so an
  # unrelated key type fails fast instead of waiting out its timeout.
  # Note: this is correctness, not the fix for the slow mount on this host.
  # Adding it did not move the ~25s SessSetup stall at all.
  environment.etc."request-key.conf".text = ''
    create cifs.spnego  * * ${pkgs.cifs-utils}/bin/cifs.upcall %k
    create dns_resolver * * ${pkgs.keyutils}/bin/key.dns_resolver %k
    create *            * * ${pkgs.keyutils}/bin/keyctl negate %k 30 %S
  '';
  environment.systemPackages = [
    pkgs.cifs-utils
    pkgs.socat            # bin/hypr-monitor-repaint taps Hyprland's socket2
                          # event stream to repaint DP monitors after a KVM switch
    # Official Bambu Studio via the upstream AppImage. Replaces the nixpkgs
    # `bambu-studio` build, which renders a BLANK 3D bed on this host (in-build
    # bug — GL stack is fine: glxgears/glxinfo work, blank even under sw-render).
    # The AppImage needed an NVIDIA-EGL fix to render — details in the pkg file.
    bambu-studio-appimage
    pkgs.orca-slicer     # Bambu Studio fork — alternative slicer for the A1
                         # (AMS, multicolor). Kept alongside as a fallback.
  ];

  # ---- Daily offsite/local backups
  # NixOS has no /etc/cron.daily, so these run as systemd timers.
  #
  # The units name INSTALLED COMMANDS under /usr/local/bin, not scripts inside
  # a checkout. A unit pointing into a working copy is a unit that stops
  # existing when a branch is switched or a directory is moved, and
  # ConditionPathExists turns that into a skipped run, which is not a failure,
  # which means OnFailure= never fires. The provisioning that installs these
  # three commands owns their content; this file only schedules them.
  #
  # ConditionPathExists still guards each one so a machine that has never been
  # provisioned boots clean. All three write to /mnt/storage. Machine-local SSH
  # target details live in /etc/nixos-secrets/ops-droplet.env:
  #   OPS_DROPLET_SSH_HOST=<local ssh alias>
  # The nightly pull authenticates with a dedicated passphrase-less key at
  # ~/.ssh/id_droplet_backup (the script's default) because this unit is a root
  # oneshot at midnight and cannot answer an interactive agent unlock. Override
  # with BACKUP_SSH_KEY in the EnvironmentFile if it ever lives elsewhere.
  systemd.services.download-droplet-backups = {
    description = "Sync production droplet backups to /mnt/storage";
    # gnugrep, gnused and bzip2 are not in coreutils and the script uses all
    # three. A unit's PATH is only what it declares, so a tool that is on the
    # human's PATH is absent here and the run dies at the first line that needs
    # it, part-way through, having already done some of the work. That is how
    # this was found: `awk: command not found` mid-run, and the empty output it
    # produced was then misread as a different fault entirely. The scripts now
    # check their own dependencies up front and name what is missing.
    path = with pkgs; [ bash coreutils findutils gnugrep gnused bzip2 rsync openssh getent libnotify ];
    serviceConfig = {
      Type = "oneshot";
      EnvironmentFile = "-/etc/nixos-secrets/ops-droplet.env";
      ExecStart = "/usr/local/bin/download-droplet-backups";
    };
    unitConfig = {
      ConditionPathExists = "/usr/local/bin/download-droplet-backups";
      # never write into an unmounted /mnt/storage (root subvol)
      ConditionPathIsMountPoint = "/mnt/storage";
      OnFailure = "backup-notify-failure@%n.service";
      OnSuccess = "backup-notify-recovered@%n.service";
    };
  };
  systemd.timers.download-droplet-backups = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "daily";
      Persistent = true;
    };
  };

  systemd.services.backup-local-state = {
    description = "Back up beads DBs + Claude config to /mnt/storage";
    path = with pkgs; [ bash coreutils findutils rsync gnutar gzip jq libnotify getent ]
      ++ [ "/run/wrappers" ];  # su (for the desktop notification)
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "/usr/local/bin/backup-local-state";
    };
    unitConfig = {
      ConditionPathExists = "/usr/local/bin/backup-local-state";
      ConditionPathIsMountPoint = "/mnt/storage";
      OnFailure = "backup-notify-failure@%n.service";
      OnSuccess = "backup-notify-recovered@%n.service";
    };
  };
  systemd.timers.backup-local-state = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "daily";
      Persistent = true;
    };
  };

  # Reads what the two units above left on disk and alarms when a tree is
  # stale. It exists because both of them once reported success for a week
  # while writing nothing: a job that checks its own work cannot catch the
  # case where it never ran, so this is a separate unit on a separate
  # schedule with the same OnFailure=.
  #
  # ConditionPathIsMountPoint matters more here than anywhere else. Without
  # it an unmounted drive makes every tree look missing and the alarm fires
  # for the wrong reason, which is how people learn to ignore an alarm.
  systemd.services.check-backup-freshness = {
    description = "Alarm when the backup trees on /mnt/storage go stale";
    path = with pkgs; [ bash coreutils findutils getent libnotify ]
      ++ [ "/run/wrappers" ];  # su (for the desktop notification)
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "/usr/local/bin/check-backup-freshness";
    };
    unitConfig = {
      ConditionPathExists = "/usr/local/bin/check-backup-freshness";
      ConditionPathIsMountPoint = "/mnt/storage";
      OnFailure = "backup-notify-failure@%n.service";
      OnSuccess = "backup-notify-recovered@%n.service";
    };
  };
  systemd.timers.check-backup-freshness = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      # Midday, hours after the nightly pull, so it reports on a finished run
      # rather than racing one.
      OnCalendar = "12:00";
      Persistent = true;
    };
  };

  # ---- daily copy of Downloads 3D models to storage (dotfiles-577/44y) ----
  # bin/sync-3d-downloads copies ~/Downloads *.stl/*.3mf to /mnt/storage/3d
  # (flat, copy-only — never deletes, source kept). Downloads is the only
  # place browser-downloaded models land, so nothing else is scanned. Runs
  # as tom; skips cleanly when the drive is absent.
  systemd.services.sync-3d-downloads = {
    description = "Copy ~/Downloads *.stl/*.3mf to /mnt/storage/3d";
    path = with pkgs; [ bash coreutils findutils rsync util-linux ];
    serviceConfig = {
      Type = "oneshot";
      User = "tom";
      ExecStart = "${pkgs.bash}/bin/bash ${homeDir}/code/tomfordweb/dotfiles/bin/sync-3d-downloads";
    };
    unitConfig = {
      ConditionPathExists = "${homeDir}/code/tomfordweb/dotfiles/bin/sync-3d-downloads";
      ConditionPathIsMountPoint = "/mnt/storage";
      OnFailure = "backup-notify-failure@%n.service";
      OnSuccess = "backup-notify-recovered@%n.service";
    };
  };
  systemd.timers.sync-3d-downloads = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "daily";
      Persistent = true;
    };
  };

  # ---- red "on fire" alert on ANY backup failure (dotfiles-tki) ------
  # The backup scripts' own notify-send fires only on their LAST line
  # (completion), and the OPS_DROPLET_SSH_HOST :?-exit dies before ever
  # reaching it — so failures were silent. systemd knows the real exit
  # code, so hang this template off each unit's OnFailure=. It fires a
  # mako urgency=critical toast (red border + dark-red bg + persistent,
  # already styled that way in config/mako/config) naming the dead unit.
  # Runs as tom with the session bus address so notify-send reaches the
  # graphical session. %n of the failing unit → this template's instance.
  systemd.services."backup-notify-failure@" = {
    description = "🔥 critical desktop alert when %i fails";
    serviceConfig = {
      Type = "oneshot";
      User = "tom";
      Environment = "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus";
    };
    scriptArgs = "%i";
    # One live alert per failing unit, keyed on the unit's own name.
    #
    # These are critical and never expire, so a job failing nightly left a toast
    # per night. 110 had accumulated across all the backup notifications before
    # anyone counted, and a wall of identical unread alarms is wallpaper: the
    # one that matters is somewhere in it, and clearing them is manual work
    # nobody does.
    #
    # The synchronous hint makes mako REPLACE the toast carrying the same tag
    # rather than stack beside it. Tagged per unit (%i) so a download failure
    # never hides a local-state failure — they are different jobs and both need
    # to be visible. Repeat failures of the same unit collapse into one.
    #
    # Clearing it on recovery is backup-notify-recovered@ below, hung off the
    # same units' OnSuccess=.
    script = ''
      # Marker so the recovery unit knows there was something to clear. In
      # XDG_RUNTIME_DIR, which is tmpfs: it dies at reboot, and so does the
      # toast it describes, so the two cannot disagree.
      mkdir -p "/run/user/1000/backup-alerts"
      : >"/run/user/1000/backup-alerts/$1"
      ${pkgs.libnotify}/bin/notify-send \
        --urgency=critical --expire-time=0 --icon=dialog-error \
        --app-name=backup-monitor \
        --hint=string:x-canonical-private-synchronous:"backup-failure-$1" \
        "🔥🔥 BACKUP FAILED 🔥🔥" \
        "$1 exited non-zero — data may NOT be backed up.
      Check: journalctl -u $1 -n 30"
    '';
  };

  # ---- and take the alert back down when the job recovers -------------------
  # A critical toast that never expires has to be dismissed by something, and
  # "the human, eventually" is how 110 of them accumulated. The failure alert
  # above outlives the failure, so a job that broke on Tuesday and has worked
  # every night since still shows Tuesday's alarm.
  #
  # There is no "dismiss by tag" call, but the synchronous hint gives one for
  # free: a NEW notification carrying the same tag replaces the old one, and if
  # it also carries a short expiry it then disappears on its own. So this sends
  # a brief, quiet "recovered" toast on the failure's tag, which removes the red
  # one and leaves nothing behind.
  #
  # Hung off OnSuccess= of the same units, so it fires exactly when the thing
  # that failed starts working again. systemd has no notion of "recovered", so
  # the failure unit drops a marker and this one only speaks when that marker is
  # there. Without that check every nightly success would emit its own toast and
  # the fix for notification noise would be four more notifications a day.
  systemd.services."backup-notify-recovered@" = {
    description = "clear the failure alert once %i succeeds";
    serviceConfig = {
      Type = "oneshot";
      User = "tom";
      Environment = "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus";
    };
    scriptArgs = "%i";
    script = ''
      marker="/run/user/1000/backup-alerts/$1"
      [ -e "$marker" ] || exit 0
      rm -f "$marker"
      ${pkgs.libnotify}/bin/notify-send \
        --urgency=low --expire-time=4000 --icon=dialog-information \
        --app-name=backup-monitor \
        --hint=string:x-canonical-private-synchronous:"backup-failure-$1" \
        "Backup recovered" \
        "$1 completed successfully."
    '';
  };
}
