-- Hyprland config. Lua, because 0.56 dropped the hyprland.conf (hyprlang)
-- lookup entirely: it reads ~/.config/hypr/hyprland.lua and nothing else,
-- and autogenerates a default stub when that is missing.
-- API reference: hyprland's own $out/share/hypr/stubs/hl.meta.lua
-- Wiki: https://wiki.hypr.land/Configuring/

local here = debug.getinfo(1, "S").source:sub(2):match("(.*/)")
local home = os.getenv("HOME")
local dotfiles = home .. "/code/tomfordweb/dotfiles"

local function exists(path)
    local f = io.open(path, "r")
    if f then f:close() return true end
    return false
end

-- cyberdream palette ($mauve, $cyan, ...) — generated by bin/rice-build from
-- rice/palette.json into colors.conf, read back by colors.lua.
local c = dofile(here .. "colors.lua")


-------------------
---- PROGRAMS -----
-------------------

local terminal    = "ghostty"
local fileManager = terminal .. " -e yazi"
local browser     = "chromium"
-- --normal-window: as a layer-shell surface wofi holds an exclusive keyboard
-- grab, so clicking outside never moves focus and close_on_focus_loss
-- (config/wofi/config) can't fire. As a normal window it floats/centers via
-- the wofi-launcher window rule below.
local menu        = "wofi --show drun --normal-window"


---------------------------
---- PER-HOST CONFIG ------
---------------------------

-- Monitor layout and workspace pinning live in configs/<hostname>.lua. Lua can
-- branch on the hostname directly, so the gitignored custom-by-hostname symlink
-- that bin/hypr-host-config used to maintain is no longer needed.
local hostname = "unknown"
local h = io.open("/etc/hostname", "r")
if h then
    hostname = (h:read("*l") or ""):gsub("%s+", "")
    h:close()
end

local hostConfig = here .. "configs/" .. hostname .. ".lua"
if exists(hostConfig) then
    dofile(hostConfig)
end

-- Machine-local overrides, outside the repo so they never leak between
-- machines. NOTE: hypr-local (NOT hypr/local) — ~/.config/hypr is a symlink
-- into the repo on home-manager hosts, so local files must live outside it.
-- A missing dir is silently skipped.
local localConfig = home .. "/.config/hypr-local/hyprland.lua"
if exists(localConfig) then
    dofile(localConfig)
end


-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    -- waybar via rice-mode so it starts with the stylesheet matching the
    -- stored mode (style.css vs style-pro.css). See bin/rice-mode.
    hl.exec_cmd("rice-mode waybar-start")
    -- awww-daemon-start, not bare awww-daemon: at login the wayland socket
    -- often isn't accepting clients yet, and awww 0.12.1 panics+coredumps
    -- instead of waiting. The wrapper retries until the daemon connects.
    hl.exec_cmd("awww-daemon-start")
    hl.exec_cmd("mako")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    -- rice-mode apply: paints the wallpaper for the stored mode (shuffle in
    -- rice mode, the pinned static image in pro mode) and matches blur/opacity.
    hl.exec_cmd("rice-mode apply")
    -- Sleep a bit — hopefully everything was initialized. Then loop wallpapers.
    hl.exec_cmd("sleep 5; hyprwallpapers_loop 300")
    -- eww widgets: ghosted desktop calendar (control center is toggled from waybar)
    hl.exec_cmd("eww daemon && eww open calendar-ghost")
    hl.dispatch(hl.dsp.focus({ workspace = 1 }))
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in  = 6,
        gaps_out = 13,

        border_size = 2,

        -- signature cyberdream gradient (palette from colors.conf)
        col = {
            active_border   = { colors = { c.mauve, c.cyan }, angle = 45 },
            inactive_border = c.surfaceDim,
        },

        -- Set to true to enable resizing windows by clicking and dragging on
        -- borders and gaps
        resize_on_border = false,

        -- See https://wiki.hypr.land/Configuring/Tearing/ before turning this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 14,
        rounding_power = 2,

        -- Transparency of focused and unfocused windows
        active_opacity     = 0.95,
        inactive_opacity   = 0.88,
        fullscreen_opacity = 1.0,

        shadow = {
            enabled        = true,
            range          = 20,
            render_power   = 3,
            color          = c.mauveGlow,
            color_inactive = c.shadowDim,
        },

        blur = {
            enabled           = true,
            size              = 8,
            passes            = 3,
            new_optimizations = true,
            ignore_opacity    = true,
            xray              = true,

            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper  = 0,
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
        background_color         = c.base,

        -- Wake every output on input. These are the ONLY way to assert
        -- "DPMS on" in 0.56: `hl.dsp.dpms()` ignores both its state and its
        -- monitor argument and merely toggles every output, so outputs that
        -- drift out of phase (one on, the rest dark) can never be brought
        -- back into line by a script — every toggle just swaps which ones are
        -- lit. With these on, a keypress or mouse move asserts on for all of
        -- them. Left at their default false, the observed failure was both
        -- Dells sitting at DRM enabled=disabled after an idle blank, with a
        -- KVM flip the only cure. See bin/hypr-dpms-wake.
        mouse_move_enables_dpms  = true,
        key_press_enables_dpms   = true,
    },

    -- XWayland (X11) apps — e.g. Bambu Studio — render blurry on fractionally
    -- scaled outputs (the HDMI-A-3 BOE panel runs scale 1.33) because Hyprland
    -- upscales their 1x buffer. force_zero_scaling makes them render at native
    -- pixels instead, i.e. crisp text. Tradeoff: on the 1.33 panel such apps
    -- appear ~25% smaller; native Wayland apps (ghostty, waybar) are
    -- unaffected, and on the scale-1 Dells this changes nothing.
    xwayland = {
        force_zero_scaling = false,
    },

    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_rules   = "",

        follow_mouse = 0,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        kb_options   = "ctrl:nocaps",
        repeat_delay = 300,
        repeat_rate  = 50,

        numlock_by_default = true, -- numpad types digits at login, not arrows

        touchpad = {
            natural_scroll = false,
        },
    },
})


-------------------
---- ANIMATIONS ---
-------------------

-- cyberdream curves
hl.curve("dream", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.0 } } })
hl.curve("glow",  { type = "bezier", points = { { 0.16, 1 },   { 0.3, 1 }   } })

-- Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
hl.curve("easeOutQuint",   { type = "bezier", points = { { 0.23, 1 },    { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear",         { type = "bezier", points = { { 0, 0 },       { 1, 1 }    } })
hl.curve("almostLinear",   { type = "bezier", points = { { 0.5, 0.5 },   { 0.75, 1 } } })
hl.curve("quick",          { type = "bezier", points = { { 0.15, 0 },    { 0.1, 1 }  } })

-- Defaults, then the cyberdream overrides folded in (windows, windowsOut,
-- border, fade and workspaces carry the cyberdream values, not the stock ones).
hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 12,   bezier = "glow" })
hl.animation({ leaf = "windows",       enabled = true, speed = 5,    bezier = "dream",        style = "popin 88%" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 5,    bezier = "dream",        style = "popin 88%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 6,    bezier = "dream" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 5,    bezier = "glow",         style = "slidefade 12%" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 7,    bezier = "quick" })


---------------
---- INPUT ----
---------------

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

hl.device({
    name        = "ploopy-corporation-ploopy-adept-trackball-mouse",
    sensitivity = -0.8,
})


---------------------
---- KEYBINDINGS ----
---------------------

-- QEMU VMs override this in ~/.config/hypr-local/hyprland.lua (the host WM
-- swallows Super); that file is dofile'd above and can set _G.mainMod.
local mainMod = _G.mainMod or "SUPER"

hl.bind(mainMod .. " + Q",         hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + B",         hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + D",         hl.dsp.window.close())
hl.bind(mainMod .. " + M",         hl.dsp.exit())
hl.bind(mainMod .. " + E",         hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V",         hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SPACE",     hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + F",         hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + P",         hl.dsp.window.pseudo()) -- dwindle
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.layout("togglesplit")) -- moved off mod+J so J = focus down

-- Force every output back on. A monitor can come out of DPMS blank stuck off
-- (dpmsStatus:false while the others read true) — this is the recovery that
-- replaces switching the KVM away and back.
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd(dotfiles .. "/bin/hypr-dpms-wake"))

-- Screenshots (bin/screenshot: saves to ~/Pictures/Screenshots + clipboard)
hl.bind("Print",                hl.dsp.exec_cmd("screenshot region")) -- drag-select a region
hl.bind("SHIFT + Print",        hl.dsp.exec_cmd("screenshot full"))   -- all outputs
hl.bind(mainMod .. " + Print",  hl.dsp.exec_cmd("screenshot active")) -- focused monitor

-- Move focus with mainMod + hjkl
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9], move the active window with + SHIFT
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("rice-mode waybar-start"))
-- rice <-> pro (presentation) mode: static wallpaper, flat bar, no blur
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("rice-mode toggle"))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exit())

-- lock screen + control center widget
hl.bind(mainMod .. " + CTRL + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + C",        hl.dsp.exec_cmd("eww open-many --toggle cc-closer control-center"))

-- whisper.cpp push-to-talk dictation. The macropad's two PTT keys emit
-- XF86Launch5 / XF86Tools (verified with wev — the firmware sends these, NOT
-- F13/F14 as an earlier flash intended; bind to what the hardware actually
-- sends). HOLD to record, RELEASE to transcribe + type. Hyprland has native
-- key-release binds, so no evdev daemon is needed here (that's the COSMIC-only
-- shim). Needs nixos/modules/whisper-dictate.nix applied (whisper-cli, wtype).
hl.bind("XF86Launch5", hl.dsp.exec_cmd("whisper-toggle start"))
hl.bind("XF86Launch5", hl.dsp.exec_cmd("whisper-toggle stop"),  { release = true })
hl.bind("XF86Tools",   hl.dsp.exec_cmd("whisper-toggle start"))
hl.bind("XF86Tools",   hl.dsp.exec_cmd("whisper-toggle stop"),  { release = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- Bambu Studio — let the main window TILE, but float + center only its
-- dialogs/popups so they never land off-screen. Bambu's blocking dialogs
-- (login, setup wizard, confirmations, errors) are X11 modal windows; the main
-- window never is — so match modal cleanly selects just the popups. Class is
-- BambuStudio for both the nix + AppImage builds.
hl.window_rule({
    name  = "bambu-dialog-center",
    match = { class = "^(BambuStudio)$", modal = true },

    float  = true,
    center = true,
})

-- wofi launches with --normal-window (see menu above) so clicking outside
-- moves focus and wofi's close_on_focus_loss can close it.
hl.window_rule({
    name  = "wofi-launcher",
    match = { class = "^(wofi)$" },

    float  = true,
    center = true,
})

hl.window_rule({
    -- Ignore maximize requests from all apps.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})

hl.window_rule({
    -- Keep focused browser content fully opaque while retaining global
    -- inactive and fullscreen opacity settings.
    name  = "keep-active-browsers-opaque",
    match = { class = "^(chromium.*|google-chrome.*|firefox|org\\.mozilla\\.firefox|brave-browser|Brave-browser)$" },

    opacity = "1.0 override 1.0 1.0",
})

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

hl.window_rule({
    name  = "floating-steam-friends-list",
    match = { class = "steam", title = "Friends List" },

    size    = "1000 1000",
    float   = true,
    no_anim = true,
})

-- DISABLED 2026-08-07: with this rule + the workspace-10 monitor pin active,
-- Hyprland 0.55.0 segfaulted in CDwindleAlgorithm::calculateWorkspace() on a
-- fullscreen dispatch (~/.cache/hyprland/hyprlandCrashReport2589.txt).
-- Re-enable and retest after a Hyprland version bump.
-- hl.window_rule({
--     name  = "steam-games-on-gaming-workspace",
--     match = { class = "^(steam_app_\\d+)$" },
--     workspace    = 10,
--     opacity      = "1.0 override",
--     no_blur      = true,
--     idle_inhibit = "fullscreen",
-- })

hl.window_rule({
    -- Bambu Studio spawns its modal dialogs ("Create Filament", preset editors)
    -- at negative coordinates, i.e. entirely off the leftmost monitor. The app
    -- then looks frozen because the invisible modal is holding input. Centering
    -- every floating Bambu window puts them back on screen.
    name  = "center-bambu-dialogs",
    match = { class = "^(BambuStudio)$", float = true },

    center = true,
})

hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- Blur the bar, launcher and notifications (glass look).
-- ignore_alpha is a THRESHOLD, not a boolean: pixels with alpha below it are
-- left unblurred. 0 blurs everything — including the fully transparent padding
-- of the layer surface, which is what painted that ugly frosted rectangle
-- around mako notifications. Keep it above the surface's own transparent
-- regions but below the real translucent panel background.
hl.layer_rule({
    name  = "glass-waybar",
    match = { namespace = "waybar" },

    blur         = true,
    ignore_alpha = 0.2,
})

hl.layer_rule({
    name  = "glass-wofi",
    match = { namespace = "wofi" },

    blur         = true,
    ignore_alpha = 0.5,
})

hl.layer_rule({
    name  = "glass-notifications",
    match = { namespace = "notifications" },

    blur         = true,
    ignore_alpha = 0.6,
})
